-- Drop existing table if exists
DROP TABLE IF EXISTS configurations;

-- Create configurations table
CREATE TABLE configurations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT NOT NULL,
    value JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create unique index on key
CREATE UNIQUE INDEX configurations_key_idx ON configurations(key);

-- Enable Row Level Security
ALTER TABLE configurations ENABLE ROW LEVEL SECURITY;

-- Create policy for anonymous users (read-only)
CREATE POLICY "Enable read access for all users"
    ON configurations
    FOR SELECT
    TO public
    USING (true);

-- Create policy for authenticated users with specific email
CREATE POLICY "Enable write access for specific users"
    ON configurations
    FOR ALL
    TO authenticated
    USING (auth.jwt() ->> 'email' = 'tiago.tauruz@gmail.com')
    WITH CHECK (auth.jwt() ->> 'email' = 'tiago.tauruz@gmail.com');

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger for updating updated_at
CREATE TRIGGER update_configurations_updated_at
    BEFORE UPDATE ON configurations
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Insert default configurations
INSERT INTO configurations (key, value) VALUES
    ('title', '"DeFi Calculator"'),
    ('description', '"Calcule seus rendimentos em criptomoedas"'),
    ('colors', '{
        "primary": "#3B82F6",
        "secondary": "#1F2937",
        "accent": "#10B981",
        "background": "#111827",
        "text": "#F3F4F6",
        "websiteText": "#FFFFFF",
        "privacyLink": "#3B82F6",
        "termsLink": "#3B82F6",
        "footerText": "#9CA3AF",
        "buyMeACoffeeText": "#F59E0B"
    }'),
    ('customTexts', '{
        "title": "DeFi Calculator",
        "description": "Calcule seus rendimentos em criptomoedas",
        "footerText": "Desenvolvido por Tiago Tauruz",
        "buyMeACoffeeText": "Buy me a coffee"
    }'),
    ('wallet1Network', '"SOL"'),
    ('wallet1Address', '"sua-carteira-sol"'),
    ('wallet2Network', '"ETH"'),
    ('wallet2Address', '"sua-carteira-eth"'),
    ('wallet3Network', '"BTC"'),
    ('wallet3Address', '"sua-carteira-btc"'),
    ('logo', '""'),
    ('favicon', '""');
